version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: db_lumen
      DB_USERNAME: lumen
      DB_PASSWORD: lumen123456

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: lumen
      POSTGRES_PASSWORD: lumen123456
      POSTGRES_DB: db_lumen
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
